// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cfeev/cfeev/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac636476ff56052c, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac636476ff56052c, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetEnergyTransferOfferRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetEnergyTransferOfferRequest) Reset()         { *m = QueryGetEnergyTransferOfferRequest{} }
func (m *QueryGetEnergyTransferOfferRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetEnergyTransferOfferRequest) ProtoMessage()    {}
func (*QueryGetEnergyTransferOfferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac636476ff56052c, []int{2}
}
func (m *QueryGetEnergyTransferOfferRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetEnergyTransferOfferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetEnergyTransferOfferRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetEnergyTransferOfferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetEnergyTransferOfferRequest.Merge(m, src)
}
func (m *QueryGetEnergyTransferOfferRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetEnergyTransferOfferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetEnergyTransferOfferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetEnergyTransferOfferRequest proto.InternalMessageInfo

func (m *QueryGetEnergyTransferOfferRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetEnergyTransferOfferResponse struct {
	EnergyTransferOffer EnergyTransferOffer `protobuf:"bytes,1,opt,name=EnergyTransferOffer,proto3" json:"EnergyTransferOffer"`
}

func (m *QueryGetEnergyTransferOfferResponse) Reset()         { *m = QueryGetEnergyTransferOfferResponse{} }
func (m *QueryGetEnergyTransferOfferResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetEnergyTransferOfferResponse) ProtoMessage()    {}
func (*QueryGetEnergyTransferOfferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac636476ff56052c, []int{3}
}
func (m *QueryGetEnergyTransferOfferResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetEnergyTransferOfferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetEnergyTransferOfferResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetEnergyTransferOfferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetEnergyTransferOfferResponse.Merge(m, src)
}
func (m *QueryGetEnergyTransferOfferResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetEnergyTransferOfferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetEnergyTransferOfferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetEnergyTransferOfferResponse proto.InternalMessageInfo

func (m *QueryGetEnergyTransferOfferResponse) GetEnergyTransferOffer() EnergyTransferOffer {
	if m != nil {
		return m.EnergyTransferOffer
	}
	return EnergyTransferOffer{}
}

type QueryAllEnergyTransferOfferRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllEnergyTransferOfferRequest) Reset()         { *m = QueryAllEnergyTransferOfferRequest{} }
func (m *QueryAllEnergyTransferOfferRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllEnergyTransferOfferRequest) ProtoMessage()    {}
func (*QueryAllEnergyTransferOfferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac636476ff56052c, []int{4}
}
func (m *QueryAllEnergyTransferOfferRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllEnergyTransferOfferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllEnergyTransferOfferRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllEnergyTransferOfferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllEnergyTransferOfferRequest.Merge(m, src)
}
func (m *QueryAllEnergyTransferOfferRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllEnergyTransferOfferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllEnergyTransferOfferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllEnergyTransferOfferRequest proto.InternalMessageInfo

func (m *QueryAllEnergyTransferOfferRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllEnergyTransferOfferResponse struct {
	EnergyTransferOffer []EnergyTransferOffer `protobuf:"bytes,1,rep,name=EnergyTransferOffer,proto3" json:"EnergyTransferOffer"`
	Pagination          *query.PageResponse   `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllEnergyTransferOfferResponse) Reset()         { *m = QueryAllEnergyTransferOfferResponse{} }
func (m *QueryAllEnergyTransferOfferResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllEnergyTransferOfferResponse) ProtoMessage()    {}
func (*QueryAllEnergyTransferOfferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac636476ff56052c, []int{5}
}
func (m *QueryAllEnergyTransferOfferResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllEnergyTransferOfferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllEnergyTransferOfferResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllEnergyTransferOfferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllEnergyTransferOfferResponse.Merge(m, src)
}
func (m *QueryAllEnergyTransferOfferResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllEnergyTransferOfferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllEnergyTransferOfferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllEnergyTransferOfferResponse proto.InternalMessageInfo

func (m *QueryAllEnergyTransferOfferResponse) GetEnergyTransferOffer() []EnergyTransferOffer {
	if m != nil {
		return m.EnergyTransferOffer
	}
	return nil
}

func (m *QueryAllEnergyTransferOfferResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetEnergyTransferRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetEnergyTransferRequest) Reset()         { *m = QueryGetEnergyTransferRequest{} }
func (m *QueryGetEnergyTransferRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetEnergyTransferRequest) ProtoMessage()    {}
func (*QueryGetEnergyTransferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac636476ff56052c, []int{6}
}
func (m *QueryGetEnergyTransferRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetEnergyTransferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetEnergyTransferRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetEnergyTransferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetEnergyTransferRequest.Merge(m, src)
}
func (m *QueryGetEnergyTransferRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetEnergyTransferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetEnergyTransferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetEnergyTransferRequest proto.InternalMessageInfo

func (m *QueryGetEnergyTransferRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetEnergyTransferResponse struct {
	EnergyTransfer EnergyTransfer `protobuf:"bytes,1,opt,name=EnergyTransfer,proto3" json:"EnergyTransfer"`
}

func (m *QueryGetEnergyTransferResponse) Reset()         { *m = QueryGetEnergyTransferResponse{} }
func (m *QueryGetEnergyTransferResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetEnergyTransferResponse) ProtoMessage()    {}
func (*QueryGetEnergyTransferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac636476ff56052c, []int{7}
}
func (m *QueryGetEnergyTransferResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetEnergyTransferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetEnergyTransferResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetEnergyTransferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetEnergyTransferResponse.Merge(m, src)
}
func (m *QueryGetEnergyTransferResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetEnergyTransferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetEnergyTransferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetEnergyTransferResponse proto.InternalMessageInfo

func (m *QueryGetEnergyTransferResponse) GetEnergyTransfer() EnergyTransfer {
	if m != nil {
		return m.EnergyTransfer
	}
	return EnergyTransfer{}
}

type QueryAllEnergyTransferRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllEnergyTransferRequest) Reset()         { *m = QueryAllEnergyTransferRequest{} }
func (m *QueryAllEnergyTransferRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllEnergyTransferRequest) ProtoMessage()    {}
func (*QueryAllEnergyTransferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac636476ff56052c, []int{8}
}
func (m *QueryAllEnergyTransferRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllEnergyTransferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllEnergyTransferRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllEnergyTransferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllEnergyTransferRequest.Merge(m, src)
}
func (m *QueryAllEnergyTransferRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllEnergyTransferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllEnergyTransferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllEnergyTransferRequest proto.InternalMessageInfo

func (m *QueryAllEnergyTransferRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllEnergyTransferResponse struct {
	EnergyTransfer []EnergyTransfer    `protobuf:"bytes,1,rep,name=EnergyTransfer,proto3" json:"EnergyTransfer"`
	Pagination     *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllEnergyTransferResponse) Reset()         { *m = QueryAllEnergyTransferResponse{} }
func (m *QueryAllEnergyTransferResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllEnergyTransferResponse) ProtoMessage()    {}
func (*QueryAllEnergyTransferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac636476ff56052c, []int{9}
}
func (m *QueryAllEnergyTransferResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllEnergyTransferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllEnergyTransferResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllEnergyTransferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllEnergyTransferResponse.Merge(m, src)
}
func (m *QueryAllEnergyTransferResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllEnergyTransferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllEnergyTransferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllEnergyTransferResponse proto.InternalMessageInfo

func (m *QueryAllEnergyTransferResponse) GetEnergyTransfer() []EnergyTransfer {
	if m != nil {
		return m.EnergyTransfer
	}
	return nil
}

func (m *QueryAllEnergyTransferResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryListOwnEnergyTransferOfferRequest struct {
	OwnerAccAddress string             `protobuf:"bytes,1,opt,name=ownerAccAddress,proto3" json:"ownerAccAddress,omitempty"`
	Pagination      *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListOwnEnergyTransferOfferRequest) Reset() {
	*m = QueryListOwnEnergyTransferOfferRequest{}
}
func (m *QueryListOwnEnergyTransferOfferRequest) String() string { return proto.CompactTextString(m) }
func (*QueryListOwnEnergyTransferOfferRequest) ProtoMessage()    {}
func (*QueryListOwnEnergyTransferOfferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac636476ff56052c, []int{10}
}
func (m *QueryListOwnEnergyTransferOfferRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListOwnEnergyTransferOfferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListOwnEnergyTransferOfferRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListOwnEnergyTransferOfferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListOwnEnergyTransferOfferRequest.Merge(m, src)
}
func (m *QueryListOwnEnergyTransferOfferRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryListOwnEnergyTransferOfferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListOwnEnergyTransferOfferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListOwnEnergyTransferOfferRequest proto.InternalMessageInfo

func (m *QueryListOwnEnergyTransferOfferRequest) GetOwnerAccAddress() string {
	if m != nil {
		return m.OwnerAccAddress
	}
	return ""
}

func (m *QueryListOwnEnergyTransferOfferRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryListOwnEnergyTransferOfferResponse struct {
	EnergyTransferOffer []EnergyTransferOffer `protobuf:"bytes,1,rep,name=energyTransferOffer,proto3" json:"energyTransferOffer"`
	Pagination          *query.PageResponse   `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListOwnEnergyTransferOfferResponse) Reset() {
	*m = QueryListOwnEnergyTransferOfferResponse{}
}
func (m *QueryListOwnEnergyTransferOfferResponse) String() string { return proto.CompactTextString(m) }
func (*QueryListOwnEnergyTransferOfferResponse) ProtoMessage()    {}
func (*QueryListOwnEnergyTransferOfferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac636476ff56052c, []int{11}
}
func (m *QueryListOwnEnergyTransferOfferResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListOwnEnergyTransferOfferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListOwnEnergyTransferOfferResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListOwnEnergyTransferOfferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListOwnEnergyTransferOfferResponse.Merge(m, src)
}
func (m *QueryListOwnEnergyTransferOfferResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryListOwnEnergyTransferOfferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListOwnEnergyTransferOfferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListOwnEnergyTransferOfferResponse proto.InternalMessageInfo

func (m *QueryListOwnEnergyTransferOfferResponse) GetEnergyTransferOffer() []EnergyTransferOffer {
	if m != nil {
		return m.EnergyTransferOffer
	}
	return nil
}

func (m *QueryListOwnEnergyTransferOfferResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryListOwnEnergyTransferRequest struct {
	DriverAccAddress string             `protobuf:"bytes,1,opt,name=driverAccAddress,proto3" json:"driverAccAddress,omitempty"`
	TransferStatus   int32              `protobuf:"varint,2,opt,name=transferStatus,proto3" json:"transferStatus,omitempty"`
	Pagination       *query.PageRequest `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListOwnEnergyTransferRequest) Reset()         { *m = QueryListOwnEnergyTransferRequest{} }
func (m *QueryListOwnEnergyTransferRequest) String() string { return proto.CompactTextString(m) }
func (*QueryListOwnEnergyTransferRequest) ProtoMessage()    {}
func (*QueryListOwnEnergyTransferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac636476ff56052c, []int{12}
}
func (m *QueryListOwnEnergyTransferRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListOwnEnergyTransferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListOwnEnergyTransferRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListOwnEnergyTransferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListOwnEnergyTransferRequest.Merge(m, src)
}
func (m *QueryListOwnEnergyTransferRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryListOwnEnergyTransferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListOwnEnergyTransferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListOwnEnergyTransferRequest proto.InternalMessageInfo

func (m *QueryListOwnEnergyTransferRequest) GetDriverAccAddress() string {
	if m != nil {
		return m.DriverAccAddress
	}
	return ""
}

func (m *QueryListOwnEnergyTransferRequest) GetTransferStatus() int32 {
	if m != nil {
		return m.TransferStatus
	}
	return 0
}

func (m *QueryListOwnEnergyTransferRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryListOwnEnergyTransferResponse struct {
	EnergyTransfer []EnergyTransfer    `protobuf:"bytes,1,rep,name=energyTransfer,proto3" json:"energyTransfer"`
	Pagination     *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListOwnEnergyTransferResponse) Reset()         { *m = QueryListOwnEnergyTransferResponse{} }
func (m *QueryListOwnEnergyTransferResponse) String() string { return proto.CompactTextString(m) }
func (*QueryListOwnEnergyTransferResponse) ProtoMessage()    {}
func (*QueryListOwnEnergyTransferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac636476ff56052c, []int{13}
}
func (m *QueryListOwnEnergyTransferResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListOwnEnergyTransferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListOwnEnergyTransferResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListOwnEnergyTransferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListOwnEnergyTransferResponse.Merge(m, src)
}
func (m *QueryListOwnEnergyTransferResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryListOwnEnergyTransferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListOwnEnergyTransferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListOwnEnergyTransferResponse proto.InternalMessageInfo

func (m *QueryListOwnEnergyTransferResponse) GetEnergyTransfer() []EnergyTransfer {
	if m != nil {
		return m.EnergyTransfer
	}
	return nil
}

func (m *QueryListOwnEnergyTransferResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "chain4energy.cfeev.cfeev.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "chain4energy.cfeev.cfeev.QueryParamsResponse")
	proto.RegisterType((*QueryGetEnergyTransferOfferRequest)(nil), "chain4energy.cfeev.cfeev.QueryGetEnergyTransferOfferRequest")
	proto.RegisterType((*QueryGetEnergyTransferOfferResponse)(nil), "chain4energy.cfeev.cfeev.QueryGetEnergyTransferOfferResponse")
	proto.RegisterType((*QueryAllEnergyTransferOfferRequest)(nil), "chain4energy.cfeev.cfeev.QueryAllEnergyTransferOfferRequest")
	proto.RegisterType((*QueryAllEnergyTransferOfferResponse)(nil), "chain4energy.cfeev.cfeev.QueryAllEnergyTransferOfferResponse")
	proto.RegisterType((*QueryGetEnergyTransferRequest)(nil), "chain4energy.cfeev.cfeev.QueryGetEnergyTransferRequest")
	proto.RegisterType((*QueryGetEnergyTransferResponse)(nil), "chain4energy.cfeev.cfeev.QueryGetEnergyTransferResponse")
	proto.RegisterType((*QueryAllEnergyTransferRequest)(nil), "chain4energy.cfeev.cfeev.QueryAllEnergyTransferRequest")
	proto.RegisterType((*QueryAllEnergyTransferResponse)(nil), "chain4energy.cfeev.cfeev.QueryAllEnergyTransferResponse")
	proto.RegisterType((*QueryListOwnEnergyTransferOfferRequest)(nil), "chain4energy.cfeev.cfeev.QueryListOwnEnergyTransferOfferRequest")
	proto.RegisterType((*QueryListOwnEnergyTransferOfferResponse)(nil), "chain4energy.cfeev.cfeev.QueryListOwnEnergyTransferOfferResponse")
	proto.RegisterType((*QueryListOwnEnergyTransferRequest)(nil), "chain4energy.cfeev.cfeev.QueryListOwnEnergyTransferRequest")
	proto.RegisterType((*QueryListOwnEnergyTransferResponse)(nil), "chain4energy.cfeev.cfeev.QueryListOwnEnergyTransferResponse")
}

func init() { proto.RegisterFile("cfeev/cfeev/query.proto", fileDescriptor_ac636476ff56052c) }

var fileDescriptor_ac636476ff56052c = []byte{
	// 816 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x97, 0xcf, 0x4f, 0x13, 0x41,
	0x14, 0xc7, 0x3b, 0xe5, 0x47, 0xe2, 0x98, 0xa0, 0x0e, 0xa0, 0xa4, 0xe2, 0x0a, 0x0b, 0xa1, 0x80,
	0xb2, 0x13, 0x90, 0x04, 0xa2, 0xa0, 0x94, 0x04, 0xb9, 0x98, 0x80, 0xf5, 0xc7, 0xc1, 0x4b, 0xb3,
	0x6d, 0x87, 0x65, 0x93, 0x65, 0xa7, 0xec, 0x4e, 0xf9, 0x11, 0xc2, 0x85, 0xb3, 0x07, 0x13, 0x6f,
	0xfe, 0x0d, 0xc6, 0xb3, 0x37, 0x43, 0x8c, 0x09, 0x47, 0x12, 0x35, 0xd1, 0x8b, 0x31, 0xe0, 0xc1,
	0x3f, 0xc3, 0x74, 0x66, 0x2a, 0xed, 0x76, 0x7f, 0xb4, 0xa5, 0x5c, 0x16, 0x32, 0xf3, 0xde, 0xbc,
	0xef, 0xe7, 0xbd, 0x7d, 0xf3, 0xb6, 0xf0, 0x46, 0x6e, 0x8d, 0x90, 0x2d, 0x2c, 0x9e, 0x9b, 0x45,
	0xe2, 0xec, 0x6a, 0x05, 0x87, 0x32, 0x8a, 0xfa, 0x72, 0xeb, 0xba, 0x69, 0x4f, 0x13, 0x9b, 0x38,
	0xc6, 0xae, 0xc6, 0xf7, 0xc5, 0x33, 0xd1, 0x63, 0x50, 0x83, 0x72, 0x23, 0x5c, 0xfa, 0x4f, 0xd8,
	0x27, 0xfa, 0x0d, 0x4a, 0x0d, 0x8b, 0x60, 0xbd, 0x60, 0x62, 0xdd, 0xb6, 0x29, 0xd3, 0x99, 0x49,
	0x6d, 0x57, 0xee, 0x8e, 0xe7, 0xa8, 0xbb, 0x41, 0x5d, 0x9c, 0xd5, 0x5d, 0x22, 0xc2, 0xe0, 0xad,
	0xc9, 0x2c, 0x61, 0xfa, 0x24, 0x2e, 0xe8, 0x86, 0x69, 0x73, 0x63, 0x69, 0xdb, 0x57, 0x29, 0xa9,
	0xa0, 0x3b, 0xfa, 0x46, 0xf9, 0x94, 0xc1, 0xca, 0x1d, 0xa1, 0x2c, 0xc3, 0x1c, 0xdd, 0x76, 0xd7,
	0x88, 0x23, 0x4d, 0x92, 0x21, 0x26, 0x19, 0xba, 0xf6, 0xdf, 0x50, 0xed, 0x81, 0xe8, 0x69, 0x49,
	0xc7, 0x2a, 0x0f, 0x90, 0x26, 0x9b, 0x45, 0xe2, 0x32, 0xf5, 0x05, 0xec, 0xae, 0x5a, 0x75, 0x0b,
	0xd4, 0x76, 0x09, 0x7a, 0x08, 0x3b, 0x85, 0x90, 0x3e, 0x30, 0x00, 0x46, 0x2f, 0x4f, 0x0d, 0x68,
	0x41, 0xd9, 0xd1, 0x84, 0xe7, 0x62, 0xfb, 0xd1, 0xaf, 0xdb, 0xb1, 0xb4, 0xf4, 0x52, 0xa7, 0xa1,
	0xca, 0x8f, 0x5d, 0x26, 0x6c, 0x89, 0xbb, 0x3c, 0x97, 0x92, 0x56, 0x4a, 0x8a, 0x64, 0x70, 0xd4,
	0x05, 0xe3, 0x66, 0x9e, 0x47, 0x68, 0x4f, 0xc7, 0xcd, 0xbc, 0xfa, 0x1a, 0xc0, 0xa1, 0x50, 0x37,
	0xa9, 0x8e, 0xc0, 0x6e, 0x9f, 0x6d, 0x29, 0x75, 0x22, 0x58, 0xaa, 0x8f, 0x93, 0xd4, 0xed, 0x77,
	0x9e, 0x6a, 0x49, 0x88, 0x94, 0x65, 0x85, 0x40, 0x3c, 0x86, 0xf0, 0xac, 0xa2, 0x52, 0xc3, 0x88,
	0x26, 0xca, 0xaf, 0x95, 0xca, 0xaf, 0x89, 0xb7, 0x4c, 0x96, 0x5f, 0x5b, 0xd5, 0x0d, 0x22, 0x7d,
	0xd3, 0x15, 0x9e, 0xea, 0xf7, 0x32, 0x7c, 0x50, 0xb8, 0x28, 0xf8, 0xb6, 0x56, 0xc2, 0xa3, 0xe5,
	0x2a, 0xac, 0x38, 0xc7, 0x4a, 0x46, 0x62, 0x09, 0x8d, 0x55, 0x5c, 0x18, 0xde, 0xf2, 0xaf, 0x69,
	0xd0, 0x5b, 0xb0, 0x03, 0x95, 0x20, 0x07, 0x99, 0x82, 0x97, 0xb0, 0xab, 0x7a, 0x47, 0xa6, 0x7d,
	0xb4, 0x5e, 0x7a, 0x09, 0xee, 0x39, 0x45, 0x35, 0xa4, 0xd4, 0x9a, 0x0a, 0xb4, 0xba, 0xd6, 0x87,
	0x40, 0x32, 0xfa, 0x44, 0x0a, 0x61, 0x6c, 0x3b, 0x3f, 0x63, 0xeb, 0xea, 0xfa, 0x0e, 0xc0, 0x11,
	0xce, 0xf0, 0xc4, 0x74, 0xd9, 0xca, 0xb6, 0x1d, 0xd2, 0x22, 0xa3, 0xf0, 0x0a, 0xdd, 0xb6, 0x89,
	0x93, 0xca, 0xe5, 0x52, 0xf9, 0xbc, 0x43, 0x5c, 0x71, 0xad, 0x5c, 0x4a, 0x7b, 0x97, 0x3d, 0x09,
	0x8e, 0x37, 0x9d, 0xe0, 0x9f, 0x00, 0x26, 0x23, 0xc5, 0x9d, 0x35, 0x14, 0x69, 0x71, 0x43, 0x91,
	0x8b, 0x6c, 0xa8, 0x4f, 0x00, 0x0e, 0x06, 0xb3, 0x95, 0x73, 0x3e, 0x0e, 0xaf, 0xe6, 0x1d, 0x73,
	0xcb, 0x27, 0xe9, 0x35, 0xeb, 0x68, 0x04, 0x76, 0x95, 0x47, 0xc6, 0x33, 0xa6, 0xb3, 0xa2, 0xcb,
	0xe5, 0x75, 0xa4, 0x3d, 0xab, 0x9e, 0xea, 0xb4, 0x35, 0x5d, 0x9d, 0x2f, 0x40, 0xde, 0xac, 0x01,
	0x04, 0x67, 0x2d, 0x40, 0x5a, 0xd2, 0x02, 0xe4, 0x62, 0x5a, 0x60, 0xea, 0x23, 0x84, 0x1d, 0x9c,
	0x03, 0x1d, 0x00, 0xd8, 0x29, 0x06, 0x21, 0xba, 0x1b, 0xac, 0xae, 0x76, 0xfe, 0x26, 0x26, 0xea,
	0xb4, 0x16, 0xd1, 0xd5, 0x9b, 0x07, 0x5f, 0xff, 0xbc, 0x8d, 0xf7, 0xa2, 0x6e, 0x5c, 0xfb, 0xcd,
	0x80, 0x3e, 0x03, 0xdf, 0xd1, 0x80, 0xe6, 0x22, 0x62, 0x84, 0x0e, 0xe9, 0xc4, 0x7c, 0x93, 0xde,
	0x52, 0x31, 0xe6, 0x8a, 0xc7, 0x50, 0x12, 0x47, 0x7e, 0xa8, 0xe0, 0x3d, 0x33, 0xbf, 0x8f, 0x0e,
	0x01, 0xbc, 0xee, 0x73, 0x60, 0xca, 0xb2, 0x22, 0x41, 0x42, 0x07, 0x75, 0x24, 0x48, 0xf8, 0xdc,
	0x55, 0xc7, 0x39, 0xc8, 0x30, 0x52, 0xa3, 0x41, 0xd0, 0x07, 0xe0, 0xbd, 0xbd, 0xd1, 0x4c, 0xa3,
	0x69, 0x2c, 0xcb, 0x9e, 0x6d, 0xdc, 0x51, 0x2a, 0x1e, 0xe3, 0x8a, 0x87, 0xd0, 0x60, 0x98, 0x62,
	0x91, 0xf4, 0xf7, 0x00, 0x5e, 0xab, 0x3e, 0xa5, 0x94, 0xef, 0x99, 0x46, 0x33, 0x56, 0xaf, 0xe6,
	0xc0, 0xb1, 0xa7, 0x0e, 0x73, 0xcd, 0x0a, 0xea, 0x0f, 0xd3, 0x8c, 0xfe, 0x02, 0x98, 0x08, 0xbe,
	0xd9, 0xd1, 0x42, 0x44, 0xf8, 0xc8, 0x89, 0x95, 0x48, 0x9d, 0xe3, 0x04, 0x49, 0xb2, 0xc4, 0x49,
	0x1e, 0xa1, 0xf9, 0x2a, 0x12, 0xcb, 0x74, 0x59, 0x86, 0x6e, 0xdb, 0x99, 0x80, 0x0e, 0xf0, 0x0c,
	0xc4, 0x7d, 0xf4, 0x0d, 0xc0, 0x5e, 0xdf, 0x68, 0xe8, 0x41, 0x33, 0x1a, 0xcb, 0x80, 0x73, 0xcd,
	0x39, 0x4b, 0xb6, 0x05, 0xce, 0x76, 0x1f, 0xcd, 0xd6, 0xc5, 0x86, 0xf7, 0xbc, 0x13, 0x67, 0x7f,
	0x71, 0xe9, 0xe8, 0x44, 0x01, 0xc7, 0x27, 0x0a, 0xf8, 0x7d, 0xa2, 0x80, 0x37, 0xa7, 0x4a, 0xec,
	0xf8, 0x54, 0x89, 0xfd, 0x38, 0x55, 0x62, 0xaf, 0xee, 0x18, 0x26, 0x5b, 0x2f, 0x66, 0xb5, 0x1c,
	0xdd, 0xc0, 0x95, 0x1a, 0x65, 0x90, 0x1d, 0xf9, 0x97, 0xed, 0x16, 0x88, 0x9b, 0xed, 0xe4, 0xbf,
	0x6d, 0xee, 0xfd, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x7c, 0xfe, 0xdb, 0x3d, 0xd6, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a EnergyTransferOffer by id.
	EnergyTransferOffer(ctx context.Context, in *QueryGetEnergyTransferOfferRequest, opts ...grpc.CallOption) (*QueryGetEnergyTransferOfferResponse, error)
	// Queries a list of EnergyTransferOffer items.
	EnergyTransferOfferAll(ctx context.Context, in *QueryAllEnergyTransferOfferRequest, opts ...grpc.CallOption) (*QueryAllEnergyTransferOfferResponse, error)
	// Queries a EnergyTransfer by id.
	EnergyTransfer(ctx context.Context, in *QueryGetEnergyTransferRequest, opts ...grpc.CallOption) (*QueryGetEnergyTransferResponse, error)
	// Queries a list of EnergyTransfer items.
	EnergyTransferAll(ctx context.Context, in *QueryAllEnergyTransferRequest, opts ...grpc.CallOption) (*QueryAllEnergyTransferResponse, error)
	// Queries a list of ListOwnEnergyTransferOffer items.
	ListOwnEnergyTransferOffer(ctx context.Context, in *QueryListOwnEnergyTransferOfferRequest, opts ...grpc.CallOption) (*QueryListOwnEnergyTransferOfferResponse, error)
	// Queries a list of ListOwnEnergyTransfer items.
	ListOwnEnergyTransfer(ctx context.Context, in *QueryListOwnEnergyTransferRequest, opts ...grpc.CallOption) (*QueryListOwnEnergyTransferResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/chain4energy.cfeev.cfeev.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) EnergyTransferOffer(ctx context.Context, in *QueryGetEnergyTransferOfferRequest, opts ...grpc.CallOption) (*QueryGetEnergyTransferOfferResponse, error) {
	out := new(QueryGetEnergyTransferOfferResponse)
	err := c.cc.Invoke(ctx, "/chain4energy.cfeev.cfeev.Query/EnergyTransferOffer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) EnergyTransferOfferAll(ctx context.Context, in *QueryAllEnergyTransferOfferRequest, opts ...grpc.CallOption) (*QueryAllEnergyTransferOfferResponse, error) {
	out := new(QueryAllEnergyTransferOfferResponse)
	err := c.cc.Invoke(ctx, "/chain4energy.cfeev.cfeev.Query/EnergyTransferOfferAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) EnergyTransfer(ctx context.Context, in *QueryGetEnergyTransferRequest, opts ...grpc.CallOption) (*QueryGetEnergyTransferResponse, error) {
	out := new(QueryGetEnergyTransferResponse)
	err := c.cc.Invoke(ctx, "/chain4energy.cfeev.cfeev.Query/EnergyTransfer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) EnergyTransferAll(ctx context.Context, in *QueryAllEnergyTransferRequest, opts ...grpc.CallOption) (*QueryAllEnergyTransferResponse, error) {
	out := new(QueryAllEnergyTransferResponse)
	err := c.cc.Invoke(ctx, "/chain4energy.cfeev.cfeev.Query/EnergyTransferAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListOwnEnergyTransferOffer(ctx context.Context, in *QueryListOwnEnergyTransferOfferRequest, opts ...grpc.CallOption) (*QueryListOwnEnergyTransferOfferResponse, error) {
	out := new(QueryListOwnEnergyTransferOfferResponse)
	err := c.cc.Invoke(ctx, "/chain4energy.cfeev.cfeev.Query/ListOwnEnergyTransferOffer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListOwnEnergyTransfer(ctx context.Context, in *QueryListOwnEnergyTransferRequest, opts ...grpc.CallOption) (*QueryListOwnEnergyTransferResponse, error) {
	out := new(QueryListOwnEnergyTransferResponse)
	err := c.cc.Invoke(ctx, "/chain4energy.cfeev.cfeev.Query/ListOwnEnergyTransfer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a EnergyTransferOffer by id.
	EnergyTransferOffer(context.Context, *QueryGetEnergyTransferOfferRequest) (*QueryGetEnergyTransferOfferResponse, error)
	// Queries a list of EnergyTransferOffer items.
	EnergyTransferOfferAll(context.Context, *QueryAllEnergyTransferOfferRequest) (*QueryAllEnergyTransferOfferResponse, error)
	// Queries a EnergyTransfer by id.
	EnergyTransfer(context.Context, *QueryGetEnergyTransferRequest) (*QueryGetEnergyTransferResponse, error)
	// Queries a list of EnergyTransfer items.
	EnergyTransferAll(context.Context, *QueryAllEnergyTransferRequest) (*QueryAllEnergyTransferResponse, error)
	// Queries a list of ListOwnEnergyTransferOffer items.
	ListOwnEnergyTransferOffer(context.Context, *QueryListOwnEnergyTransferOfferRequest) (*QueryListOwnEnergyTransferOfferResponse, error)
	// Queries a list of ListOwnEnergyTransfer items.
	ListOwnEnergyTransfer(context.Context, *QueryListOwnEnergyTransferRequest) (*QueryListOwnEnergyTransferResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) EnergyTransferOffer(ctx context.Context, req *QueryGetEnergyTransferOfferRequest) (*QueryGetEnergyTransferOfferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnergyTransferOffer not implemented")
}
func (*UnimplementedQueryServer) EnergyTransferOfferAll(ctx context.Context, req *QueryAllEnergyTransferOfferRequest) (*QueryAllEnergyTransferOfferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnergyTransferOfferAll not implemented")
}
func (*UnimplementedQueryServer) EnergyTransfer(ctx context.Context, req *QueryGetEnergyTransferRequest) (*QueryGetEnergyTransferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnergyTransfer not implemented")
}
func (*UnimplementedQueryServer) EnergyTransferAll(ctx context.Context, req *QueryAllEnergyTransferRequest) (*QueryAllEnergyTransferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnergyTransferAll not implemented")
}
func (*UnimplementedQueryServer) ListOwnEnergyTransferOffer(ctx context.Context, req *QueryListOwnEnergyTransferOfferRequest) (*QueryListOwnEnergyTransferOfferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOwnEnergyTransferOffer not implemented")
}
func (*UnimplementedQueryServer) ListOwnEnergyTransfer(ctx context.Context, req *QueryListOwnEnergyTransferRequest) (*QueryListOwnEnergyTransferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOwnEnergyTransfer not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain4energy.cfeev.cfeev.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_EnergyTransferOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetEnergyTransferOfferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EnergyTransferOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain4energy.cfeev.cfeev.Query/EnergyTransferOffer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EnergyTransferOffer(ctx, req.(*QueryGetEnergyTransferOfferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_EnergyTransferOfferAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllEnergyTransferOfferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EnergyTransferOfferAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain4energy.cfeev.cfeev.Query/EnergyTransferOfferAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EnergyTransferOfferAll(ctx, req.(*QueryAllEnergyTransferOfferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_EnergyTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetEnergyTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EnergyTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain4energy.cfeev.cfeev.Query/EnergyTransfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EnergyTransfer(ctx, req.(*QueryGetEnergyTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_EnergyTransferAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllEnergyTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EnergyTransferAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain4energy.cfeev.cfeev.Query/EnergyTransferAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EnergyTransferAll(ctx, req.(*QueryAllEnergyTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListOwnEnergyTransferOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListOwnEnergyTransferOfferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListOwnEnergyTransferOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain4energy.cfeev.cfeev.Query/ListOwnEnergyTransferOffer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListOwnEnergyTransferOffer(ctx, req.(*QueryListOwnEnergyTransferOfferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListOwnEnergyTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListOwnEnergyTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListOwnEnergyTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain4energy.cfeev.cfeev.Query/ListOwnEnergyTransfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListOwnEnergyTransfer(ctx, req.(*QueryListOwnEnergyTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chain4energy.cfeev.cfeev.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "EnergyTransferOffer",
			Handler:    _Query_EnergyTransferOffer_Handler,
		},
		{
			MethodName: "EnergyTransferOfferAll",
			Handler:    _Query_EnergyTransferOfferAll_Handler,
		},
		{
			MethodName: "EnergyTransfer",
			Handler:    _Query_EnergyTransfer_Handler,
		},
		{
			MethodName: "EnergyTransferAll",
			Handler:    _Query_EnergyTransferAll_Handler,
		},
		{
			MethodName: "ListOwnEnergyTransferOffer",
			Handler:    _Query_ListOwnEnergyTransferOffer_Handler,
		},
		{
			MethodName: "ListOwnEnergyTransfer",
			Handler:    _Query_ListOwnEnergyTransfer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cfeev/cfeev/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetEnergyTransferOfferRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetEnergyTransferOfferRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetEnergyTransferOfferRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetEnergyTransferOfferResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetEnergyTransferOfferResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetEnergyTransferOfferResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.EnergyTransferOffer.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllEnergyTransferOfferRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllEnergyTransferOfferRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllEnergyTransferOfferRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllEnergyTransferOfferResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllEnergyTransferOfferResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllEnergyTransferOfferResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.EnergyTransferOffer) > 0 {
		for iNdEx := len(m.EnergyTransferOffer) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.EnergyTransferOffer[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetEnergyTransferRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetEnergyTransferRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetEnergyTransferRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetEnergyTransferResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetEnergyTransferResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetEnergyTransferResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.EnergyTransfer.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllEnergyTransferRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllEnergyTransferRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllEnergyTransferRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllEnergyTransferResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllEnergyTransferResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllEnergyTransferResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.EnergyTransfer) > 0 {
		for iNdEx := len(m.EnergyTransfer) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.EnergyTransfer[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryListOwnEnergyTransferOfferRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListOwnEnergyTransferOfferRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListOwnEnergyTransferOfferRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.OwnerAccAddress) > 0 {
		i -= len(m.OwnerAccAddress)
		copy(dAtA[i:], m.OwnerAccAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.OwnerAccAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryListOwnEnergyTransferOfferResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListOwnEnergyTransferOfferResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListOwnEnergyTransferOfferResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.EnergyTransferOffer) > 0 {
		for iNdEx := len(m.EnergyTransferOffer) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.EnergyTransferOffer[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryListOwnEnergyTransferRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListOwnEnergyTransferRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListOwnEnergyTransferRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.TransferStatus != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.TransferStatus))
		i--
		dAtA[i] = 0x10
	}
	if len(m.DriverAccAddress) > 0 {
		i -= len(m.DriverAccAddress)
		copy(dAtA[i:], m.DriverAccAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.DriverAccAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryListOwnEnergyTransferResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListOwnEnergyTransferResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListOwnEnergyTransferResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.EnergyTransfer) > 0 {
		for iNdEx := len(m.EnergyTransfer) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.EnergyTransfer[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetEnergyTransferOfferRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetEnergyTransferOfferResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.EnergyTransferOffer.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllEnergyTransferOfferRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllEnergyTransferOfferResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.EnergyTransferOffer) > 0 {
		for _, e := range m.EnergyTransferOffer {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetEnergyTransferRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetEnergyTransferResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.EnergyTransfer.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllEnergyTransferRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllEnergyTransferResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.EnergyTransfer) > 0 {
		for _, e := range m.EnergyTransfer {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListOwnEnergyTransferOfferRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OwnerAccAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListOwnEnergyTransferOfferResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.EnergyTransferOffer) > 0 {
		for _, e := range m.EnergyTransferOffer {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListOwnEnergyTransferRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DriverAccAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.TransferStatus != 0 {
		n += 1 + sovQuery(uint64(m.TransferStatus))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListOwnEnergyTransferResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.EnergyTransfer) > 0 {
		for _, e := range m.EnergyTransfer {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetEnergyTransferOfferRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetEnergyTransferOfferRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetEnergyTransferOfferRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetEnergyTransferOfferResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetEnergyTransferOfferResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetEnergyTransferOfferResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnergyTransferOffer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.EnergyTransferOffer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllEnergyTransferOfferRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllEnergyTransferOfferRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllEnergyTransferOfferRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllEnergyTransferOfferResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllEnergyTransferOfferResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllEnergyTransferOfferResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnergyTransferOffer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EnergyTransferOffer = append(m.EnergyTransferOffer, EnergyTransferOffer{})
			if err := m.EnergyTransferOffer[len(m.EnergyTransferOffer)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetEnergyTransferRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetEnergyTransferRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetEnergyTransferRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetEnergyTransferResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetEnergyTransferResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetEnergyTransferResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnergyTransfer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.EnergyTransfer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllEnergyTransferRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllEnergyTransferRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllEnergyTransferRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllEnergyTransferResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllEnergyTransferResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllEnergyTransferResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnergyTransfer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EnergyTransfer = append(m.EnergyTransfer, EnergyTransfer{})
			if err := m.EnergyTransfer[len(m.EnergyTransfer)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListOwnEnergyTransferOfferRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListOwnEnergyTransferOfferRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListOwnEnergyTransferOfferRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnerAccAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OwnerAccAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListOwnEnergyTransferOfferResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListOwnEnergyTransferOfferResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListOwnEnergyTransferOfferResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnergyTransferOffer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EnergyTransferOffer = append(m.EnergyTransferOffer, EnergyTransferOffer{})
			if err := m.EnergyTransferOffer[len(m.EnergyTransferOffer)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListOwnEnergyTransferRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListOwnEnergyTransferRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListOwnEnergyTransferRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DriverAccAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DriverAccAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransferStatus", wireType)
			}
			m.TransferStatus = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TransferStatus |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListOwnEnergyTransferResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListOwnEnergyTransferResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListOwnEnergyTransferResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnergyTransfer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EnergyTransfer = append(m.EnergyTransfer, EnergyTransfer{})
			if err := m.EnergyTransfer[len(m.EnergyTransfer)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
