// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cfeev/cfeev/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgPublishEnergyTransferOffer struct {
	Creator   string    `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	ChargerId string    `protobuf:"bytes,2,opt,name=chargerId,proto3" json:"chargerId,omitempty"`
	Tariff    int32     `protobuf:"varint,3,opt,name=tariff,proto3" json:"tariff,omitempty"`
	Location  *Location `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Name      string    `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	PlugType  PlugType  `protobuf:"varint,6,opt,name=plugType,proto3,enum=chain4energy.cfeev.cfeev.PlugType" json:"plugType,omitempty"`
}

func (m *MsgPublishEnergyTransferOffer) Reset()         { *m = MsgPublishEnergyTransferOffer{} }
func (m *MsgPublishEnergyTransferOffer) String() string { return proto.CompactTextString(m) }
func (*MsgPublishEnergyTransferOffer) ProtoMessage()    {}
func (*MsgPublishEnergyTransferOffer) Descriptor() ([]byte, []int) {
	return fileDescriptor_202d1d64d91f912c, []int{0}
}
func (m *MsgPublishEnergyTransferOffer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgPublishEnergyTransferOffer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgPublishEnergyTransferOffer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgPublishEnergyTransferOffer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPublishEnergyTransferOffer.Merge(m, src)
}
func (m *MsgPublishEnergyTransferOffer) XXX_Size() int {
	return m.Size()
}
func (m *MsgPublishEnergyTransferOffer) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPublishEnergyTransferOffer.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPublishEnergyTransferOffer proto.InternalMessageInfo

func (m *MsgPublishEnergyTransferOffer) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgPublishEnergyTransferOffer) GetChargerId() string {
	if m != nil {
		return m.ChargerId
	}
	return ""
}

func (m *MsgPublishEnergyTransferOffer) GetTariff() int32 {
	if m != nil {
		return m.Tariff
	}
	return 0
}

func (m *MsgPublishEnergyTransferOffer) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *MsgPublishEnergyTransferOffer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgPublishEnergyTransferOffer) GetPlugType() PlugType {
	if m != nil {
		return m.PlugType
	}
	return PlugType_Type1
}

type MsgPublishEnergyTransferOfferResponse struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgPublishEnergyTransferOfferResponse) Reset()         { *m = MsgPublishEnergyTransferOfferResponse{} }
func (m *MsgPublishEnergyTransferOfferResponse) String() string { return proto.CompactTextString(m) }
func (*MsgPublishEnergyTransferOfferResponse) ProtoMessage()    {}
func (*MsgPublishEnergyTransferOfferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_202d1d64d91f912c, []int{1}
}
func (m *MsgPublishEnergyTransferOfferResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgPublishEnergyTransferOfferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgPublishEnergyTransferOfferResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgPublishEnergyTransferOfferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPublishEnergyTransferOfferResponse.Merge(m, src)
}
func (m *MsgPublishEnergyTransferOfferResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgPublishEnergyTransferOfferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPublishEnergyTransferOfferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPublishEnergyTransferOfferResponse proto.InternalMessageInfo

func (m *MsgPublishEnergyTransferOfferResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgStartEnergyTransferRequest struct {
	Creator               string      `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	EnergyTransferOfferId uint64      `protobuf:"varint,2,opt,name=energyTransferOfferId,proto3" json:"energyTransferOfferId,omitempty"`
	ChargerId             string      `protobuf:"bytes,3,opt,name=chargerId,proto3" json:"chargerId,omitempty"`
	OwnerAccountAddress   string      `protobuf:"bytes,4,opt,name=ownerAccountAddress,proto3" json:"ownerAccountAddress,omitempty"`
	OfferedTariff         string      `protobuf:"bytes,5,opt,name=offeredTariff,proto3" json:"offeredTariff,omitempty"`
	Collateral            *types.Coin `protobuf:"bytes,6,opt,name=collateral,proto3" json:"collateral,omitempty"`
	EnergyToTransfer      int32       `protobuf:"varint,7,opt,name=energyToTransfer,proto3" json:"energyToTransfer,omitempty"`
}

func (m *MsgStartEnergyTransferRequest) Reset()         { *m = MsgStartEnergyTransferRequest{} }
func (m *MsgStartEnergyTransferRequest) String() string { return proto.CompactTextString(m) }
func (*MsgStartEnergyTransferRequest) ProtoMessage()    {}
func (*MsgStartEnergyTransferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_202d1d64d91f912c, []int{2}
}
func (m *MsgStartEnergyTransferRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgStartEnergyTransferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgStartEnergyTransferRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgStartEnergyTransferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgStartEnergyTransferRequest.Merge(m, src)
}
func (m *MsgStartEnergyTransferRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgStartEnergyTransferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgStartEnergyTransferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgStartEnergyTransferRequest proto.InternalMessageInfo

func (m *MsgStartEnergyTransferRequest) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgStartEnergyTransferRequest) GetEnergyTransferOfferId() uint64 {
	if m != nil {
		return m.EnergyTransferOfferId
	}
	return 0
}

func (m *MsgStartEnergyTransferRequest) GetChargerId() string {
	if m != nil {
		return m.ChargerId
	}
	return ""
}

func (m *MsgStartEnergyTransferRequest) GetOwnerAccountAddress() string {
	if m != nil {
		return m.OwnerAccountAddress
	}
	return ""
}

func (m *MsgStartEnergyTransferRequest) GetOfferedTariff() string {
	if m != nil {
		return m.OfferedTariff
	}
	return ""
}

func (m *MsgStartEnergyTransferRequest) GetCollateral() *types.Coin {
	if m != nil {
		return m.Collateral
	}
	return nil
}

func (m *MsgStartEnergyTransferRequest) GetEnergyToTransfer() int32 {
	if m != nil {
		return m.EnergyToTransfer
	}
	return 0
}

type MsgStartEnergyTransferRequestResponse struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgStartEnergyTransferRequestResponse) Reset()         { *m = MsgStartEnergyTransferRequestResponse{} }
func (m *MsgStartEnergyTransferRequestResponse) String() string { return proto.CompactTextString(m) }
func (*MsgStartEnergyTransferRequestResponse) ProtoMessage()    {}
func (*MsgStartEnergyTransferRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_202d1d64d91f912c, []int{3}
}
func (m *MsgStartEnergyTransferRequestResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgStartEnergyTransferRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgStartEnergyTransferRequestResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgStartEnergyTransferRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgStartEnergyTransferRequestResponse.Merge(m, src)
}
func (m *MsgStartEnergyTransferRequestResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgStartEnergyTransferRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgStartEnergyTransferRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgStartEnergyTransferRequestResponse proto.InternalMessageInfo

func (m *MsgStartEnergyTransferRequestResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgEnergyTransferStartedRequest struct {
	Creator          string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	EnergyTransferId uint64 `protobuf:"varint,2,opt,name=energyTransferId,proto3" json:"energyTransferId,omitempty"`
	ChargerId        string `protobuf:"bytes,3,opt,name=chargerId,proto3" json:"chargerId,omitempty"`
	Info             string `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"`
}

func (m *MsgEnergyTransferStartedRequest) Reset()         { *m = MsgEnergyTransferStartedRequest{} }
func (m *MsgEnergyTransferStartedRequest) String() string { return proto.CompactTextString(m) }
func (*MsgEnergyTransferStartedRequest) ProtoMessage()    {}
func (*MsgEnergyTransferStartedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_202d1d64d91f912c, []int{4}
}
func (m *MsgEnergyTransferStartedRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgEnergyTransferStartedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgEnergyTransferStartedRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgEnergyTransferStartedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgEnergyTransferStartedRequest.Merge(m, src)
}
func (m *MsgEnergyTransferStartedRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgEnergyTransferStartedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgEnergyTransferStartedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgEnergyTransferStartedRequest proto.InternalMessageInfo

func (m *MsgEnergyTransferStartedRequest) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgEnergyTransferStartedRequest) GetEnergyTransferId() uint64 {
	if m != nil {
		return m.EnergyTransferId
	}
	return 0
}

func (m *MsgEnergyTransferStartedRequest) GetChargerId() string {
	if m != nil {
		return m.ChargerId
	}
	return ""
}

func (m *MsgEnergyTransferStartedRequest) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

type MsgEnergyTransferStartedRequestResponse struct {
}

func (m *MsgEnergyTransferStartedRequestResponse) Reset() {
	*m = MsgEnergyTransferStartedRequestResponse{}
}
func (m *MsgEnergyTransferStartedRequestResponse) String() string { return proto.CompactTextString(m) }
func (*MsgEnergyTransferStartedRequestResponse) ProtoMessage()    {}
func (*MsgEnergyTransferStartedRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_202d1d64d91f912c, []int{5}
}
func (m *MsgEnergyTransferStartedRequestResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgEnergyTransferStartedRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgEnergyTransferStartedRequestResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgEnergyTransferStartedRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgEnergyTransferStartedRequestResponse.Merge(m, src)
}
func (m *MsgEnergyTransferStartedRequestResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgEnergyTransferStartedRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgEnergyTransferStartedRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgEnergyTransferStartedRequestResponse proto.InternalMessageInfo

type MsgEnergyTransferCompletedRequest struct {
	Creator          string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	EnergyTransferId uint64 `protobuf:"varint,2,opt,name=energyTransferId,proto3" json:"energyTransferId,omitempty"`
	ChargerId        string `protobuf:"bytes,3,opt,name=chargerId,proto3" json:"chargerId,omitempty"`
	UsedServiceUnits int32  `protobuf:"varint,4,opt,name=usedServiceUnits,proto3" json:"usedServiceUnits,omitempty"`
	Info             string `protobuf:"bytes,5,opt,name=info,proto3" json:"info,omitempty"`
}

func (m *MsgEnergyTransferCompletedRequest) Reset()         { *m = MsgEnergyTransferCompletedRequest{} }
func (m *MsgEnergyTransferCompletedRequest) String() string { return proto.CompactTextString(m) }
func (*MsgEnergyTransferCompletedRequest) ProtoMessage()    {}
func (*MsgEnergyTransferCompletedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_202d1d64d91f912c, []int{6}
}
func (m *MsgEnergyTransferCompletedRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgEnergyTransferCompletedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgEnergyTransferCompletedRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgEnergyTransferCompletedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgEnergyTransferCompletedRequest.Merge(m, src)
}
func (m *MsgEnergyTransferCompletedRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgEnergyTransferCompletedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgEnergyTransferCompletedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgEnergyTransferCompletedRequest proto.InternalMessageInfo

func (m *MsgEnergyTransferCompletedRequest) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgEnergyTransferCompletedRequest) GetEnergyTransferId() uint64 {
	if m != nil {
		return m.EnergyTransferId
	}
	return 0
}

func (m *MsgEnergyTransferCompletedRequest) GetChargerId() string {
	if m != nil {
		return m.ChargerId
	}
	return ""
}

func (m *MsgEnergyTransferCompletedRequest) GetUsedServiceUnits() int32 {
	if m != nil {
		return m.UsedServiceUnits
	}
	return 0
}

func (m *MsgEnergyTransferCompletedRequest) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

type MsgEnergyTransferCompletedRequestResponse struct {
}

func (m *MsgEnergyTransferCompletedRequestResponse) Reset() {
	*m = MsgEnergyTransferCompletedRequestResponse{}
}
func (m *MsgEnergyTransferCompletedRequestResponse) String() string {
	return proto.CompactTextString(m)
}
func (*MsgEnergyTransferCompletedRequestResponse) ProtoMessage() {}
func (*MsgEnergyTransferCompletedRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_202d1d64d91f912c, []int{7}
}
func (m *MsgEnergyTransferCompletedRequestResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgEnergyTransferCompletedRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgEnergyTransferCompletedRequestResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgEnergyTransferCompletedRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgEnergyTransferCompletedRequestResponse.Merge(m, src)
}
func (m *MsgEnergyTransferCompletedRequestResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgEnergyTransferCompletedRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgEnergyTransferCompletedRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgEnergyTransferCompletedRequestResponse proto.InternalMessageInfo

type MsgCancelEnergyTransferRequest struct {
	Creator          string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	EnergyTransferId uint64 `protobuf:"varint,2,opt,name=energyTransferId,proto3" json:"energyTransferId,omitempty"`
	ChargerId        string `protobuf:"bytes,3,opt,name=chargerId,proto3" json:"chargerId,omitempty"`
	ErrorInfo        string `protobuf:"bytes,4,opt,name=errorInfo,proto3" json:"errorInfo,omitempty"`
	ErrorCode        string `protobuf:"bytes,5,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
}

func (m *MsgCancelEnergyTransferRequest) Reset()         { *m = MsgCancelEnergyTransferRequest{} }
func (m *MsgCancelEnergyTransferRequest) String() string { return proto.CompactTextString(m) }
func (*MsgCancelEnergyTransferRequest) ProtoMessage()    {}
func (*MsgCancelEnergyTransferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_202d1d64d91f912c, []int{8}
}
func (m *MsgCancelEnergyTransferRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCancelEnergyTransferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCancelEnergyTransferRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCancelEnergyTransferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelEnergyTransferRequest.Merge(m, src)
}
func (m *MsgCancelEnergyTransferRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgCancelEnergyTransferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelEnergyTransferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelEnergyTransferRequest proto.InternalMessageInfo

func (m *MsgCancelEnergyTransferRequest) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCancelEnergyTransferRequest) GetEnergyTransferId() uint64 {
	if m != nil {
		return m.EnergyTransferId
	}
	return 0
}

func (m *MsgCancelEnergyTransferRequest) GetChargerId() string {
	if m != nil {
		return m.ChargerId
	}
	return ""
}

func (m *MsgCancelEnergyTransferRequest) GetErrorInfo() string {
	if m != nil {
		return m.ErrorInfo
	}
	return ""
}

func (m *MsgCancelEnergyTransferRequest) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

type MsgCancelEnergyTransferRequestResponse struct {
}

func (m *MsgCancelEnergyTransferRequestResponse) Reset() {
	*m = MsgCancelEnergyTransferRequestResponse{}
}
func (m *MsgCancelEnergyTransferRequestResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCancelEnergyTransferRequestResponse) ProtoMessage()    {}
func (*MsgCancelEnergyTransferRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_202d1d64d91f912c, []int{9}
}
func (m *MsgCancelEnergyTransferRequestResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCancelEnergyTransferRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCancelEnergyTransferRequestResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCancelEnergyTransferRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelEnergyTransferRequestResponse.Merge(m, src)
}
func (m *MsgCancelEnergyTransferRequestResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCancelEnergyTransferRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelEnergyTransferRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelEnergyTransferRequestResponse proto.InternalMessageInfo

type MsgRemoveEnergyOffer struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id      uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgRemoveEnergyOffer) Reset()         { *m = MsgRemoveEnergyOffer{} }
func (m *MsgRemoveEnergyOffer) String() string { return proto.CompactTextString(m) }
func (*MsgRemoveEnergyOffer) ProtoMessage()    {}
func (*MsgRemoveEnergyOffer) Descriptor() ([]byte, []int) {
	return fileDescriptor_202d1d64d91f912c, []int{10}
}
func (m *MsgRemoveEnergyOffer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRemoveEnergyOffer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRemoveEnergyOffer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRemoveEnergyOffer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRemoveEnergyOffer.Merge(m, src)
}
func (m *MsgRemoveEnergyOffer) XXX_Size() int {
	return m.Size()
}
func (m *MsgRemoveEnergyOffer) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRemoveEnergyOffer.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRemoveEnergyOffer proto.InternalMessageInfo

func (m *MsgRemoveEnergyOffer) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgRemoveEnergyOffer) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgRemoveEnergyOfferResponse struct {
}

func (m *MsgRemoveEnergyOfferResponse) Reset()         { *m = MsgRemoveEnergyOfferResponse{} }
func (m *MsgRemoveEnergyOfferResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRemoveEnergyOfferResponse) ProtoMessage()    {}
func (*MsgRemoveEnergyOfferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_202d1d64d91f912c, []int{11}
}
func (m *MsgRemoveEnergyOfferResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRemoveEnergyOfferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRemoveEnergyOfferResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRemoveEnergyOfferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRemoveEnergyOfferResponse.Merge(m, src)
}
func (m *MsgRemoveEnergyOfferResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRemoveEnergyOfferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRemoveEnergyOfferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRemoveEnergyOfferResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgPublishEnergyTransferOffer)(nil), "chain4energy.cfeev.cfeev.MsgPublishEnergyTransferOffer")
	proto.RegisterType((*MsgPublishEnergyTransferOfferResponse)(nil), "chain4energy.cfeev.cfeev.MsgPublishEnergyTransferOfferResponse")
	proto.RegisterType((*MsgStartEnergyTransferRequest)(nil), "chain4energy.cfeev.cfeev.MsgStartEnergyTransferRequest")
	proto.RegisterType((*MsgStartEnergyTransferRequestResponse)(nil), "chain4energy.cfeev.cfeev.MsgStartEnergyTransferRequestResponse")
	proto.RegisterType((*MsgEnergyTransferStartedRequest)(nil), "chain4energy.cfeev.cfeev.MsgEnergyTransferStartedRequest")
	proto.RegisterType((*MsgEnergyTransferStartedRequestResponse)(nil), "chain4energy.cfeev.cfeev.MsgEnergyTransferStartedRequestResponse")
	proto.RegisterType((*MsgEnergyTransferCompletedRequest)(nil), "chain4energy.cfeev.cfeev.MsgEnergyTransferCompletedRequest")
	proto.RegisterType((*MsgEnergyTransferCompletedRequestResponse)(nil), "chain4energy.cfeev.cfeev.MsgEnergyTransferCompletedRequestResponse")
	proto.RegisterType((*MsgCancelEnergyTransferRequest)(nil), "chain4energy.cfeev.cfeev.MsgCancelEnergyTransferRequest")
	proto.RegisterType((*MsgCancelEnergyTransferRequestResponse)(nil), "chain4energy.cfeev.cfeev.MsgCancelEnergyTransferRequestResponse")
	proto.RegisterType((*MsgRemoveEnergyOffer)(nil), "chain4energy.cfeev.cfeev.MsgRemoveEnergyOffer")
	proto.RegisterType((*MsgRemoveEnergyOfferResponse)(nil), "chain4energy.cfeev.cfeev.MsgRemoveEnergyOfferResponse")
}

func init() { proto.RegisterFile("cfeev/cfeev/tx.proto", fileDescriptor_202d1d64d91f912c) }

var fileDescriptor_202d1d64d91f912c = []byte{
	// 759 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0x4f, 0x4f, 0x13, 0x51,
	0x10, 0xe7, 0x95, 0x16, 0xec, 0x10, 0x09, 0xae, 0x68, 0xd6, 0xb5, 0xae, 0xb5, 0x51, 0x29, 0x90,
	0x6c, 0x05, 0x89, 0x48, 0x4c, 0x14, 0x6c, 0x38, 0x90, 0xd8, 0x48, 0x16, 0xbc, 0x78, 0x21, 0xdb,
	0xdd, 0xe9, 0x76, 0x93, 0xed, 0xbe, 0xfa, 0xde, 0xb6, 0x42, 0x3c, 0xfa, 0x05, 0x3c, 0x18, 0x13,
	0x12, 0x4f, 0x7e, 0x12, 0x6f, 0x7a, 0xf0, 0xc0, 0xd1, 0xa3, 0x81, 0x2f, 0x62, 0xba, 0xff, 0xda,
	0x52, 0xfa, 0x2a, 0x68, 0xbc, 0x6c, 0x76, 0xe7, 0xcd, 0x6f, 0x66, 0x7e, 0xbf, 0x99, 0x37, 0x59,
	0x98, 0x35, 0x6b, 0x88, 0xed, 0x52, 0xf8, 0xf4, 0xf7, 0xb5, 0x26, 0xa3, 0x3e, 0x95, 0x64, 0xb3,
	0x6e, 0x38, 0xde, 0x0a, 0x7a, 0xc8, 0xec, 0x03, 0x2d, 0x38, 0x0c, 0x9f, 0x8a, 0xd2, 0xeb, 0xef,
	0x52, 0xd3, 0xf0, 0x1d, 0xea, 0x85, 0x28, 0x65, 0xae, 0xf7, 0x2c, 0xc4, 0xee, 0xf9, 0xcc, 0xf0,
	0x78, 0x0d, 0xd9, 0x1e, 0xad, 0xd5, 0x90, 0x45, 0x8e, 0xaa, 0x49, 0x79, 0x83, 0xf2, 0x52, 0xd5,
	0xe0, 0x58, 0x6a, 0x2f, 0x55, 0xd1, 0x37, 0x96, 0x4a, 0x26, 0x75, 0xa2, 0x40, 0x85, 0xf7, 0x29,
	0xb8, 0x55, 0xe1, 0xf6, 0x76, 0xab, 0xea, 0x3a, 0xbc, 0xbe, 0x19, 0x44, 0xda, 0x8d, 0x02, 0xbd,
	0xec, 0xc4, 0x91, 0x64, 0x98, 0x34, 0x19, 0x1a, 0x3e, 0x65, 0x32, 0xc9, 0x93, 0x62, 0x56, 0x8f,
	0x3f, 0xa5, 0x1c, 0x64, 0xcd, 0xba, 0xc1, 0x6c, 0x64, 0x5b, 0x96, 0x9c, 0x0a, 0xce, 0xba, 0x06,
	0xe9, 0x3a, 0x4c, 0xf8, 0x06, 0x73, 0x6a, 0x35, 0x79, 0x3c, 0x4f, 0x8a, 0x19, 0x3d, 0xfa, 0x92,
	0x9e, 0xc2, 0xa5, 0x98, 0x8c, 0x9c, 0xce, 0x93, 0xe2, 0xd4, 0x72, 0x41, 0x1b, 0xa6, 0x81, 0xf6,
	0x22, 0xf2, 0xd4, 0x13, 0x8c, 0x24, 0x41, 0xda, 0x33, 0x1a, 0x28, 0x67, 0x82, 0x84, 0xc1, 0x7b,
	0x27, 0x66, 0xd3, 0x6d, 0xd9, 0xbb, 0x07, 0x4d, 0x94, 0x27, 0xf2, 0xa4, 0x38, 0x2d, 0x8a, 0xb9,
	0x1d, 0x79, 0xea, 0x09, 0xa6, 0xb0, 0x0a, 0xf7, 0x84, 0x22, 0xe8, 0xc8, 0x9b, 0xd4, 0xe3, 0x28,
	0x4d, 0x43, 0xca, 0xb1, 0x02, 0x1d, 0xd2, 0x7a, 0xca, 0xb1, 0x0a, 0x3f, 0x42, 0xf9, 0x76, 0x7c,
	0x83, 0xf9, 0xfd, 0x38, 0x1d, 0xdf, 0xb4, 0x90, 0xfb, 0x02, 0xf9, 0x56, 0xe0, 0x1a, 0x0e, 0xa6,
	0x8a, 0xa4, 0x4c, 0xeb, 0x67, 0x1f, 0xf6, 0x8b, 0x3e, 0x7e, 0x5a, 0xf4, 0x07, 0x70, 0x95, 0xbe,
	0xf5, 0x90, 0x6d, 0x98, 0x26, 0x6d, 0x79, 0xfe, 0x86, 0x65, 0x31, 0xe4, 0x3c, 0xd0, 0x39, 0xab,
	0x9f, 0x75, 0x24, 0xdd, 0x85, 0xcb, 0xc1, 0xbc, 0xa0, 0xb5, 0x1b, 0x76, 0x2b, 0xd4, 0xb5, 0xdf,
	0x28, 0xad, 0x01, 0x98, 0xd4, 0x75, 0x0d, 0x1f, 0x99, 0xe1, 0x06, 0x12, 0x4f, 0x2d, 0xdf, 0xd0,
	0xc2, 0xd9, 0xd2, 0x3a, 0xb3, 0xa5, 0x45, 0xb3, 0xa5, 0x95, 0xa9, 0xe3, 0xe9, 0x3d, 0xce, 0xd2,
	0x02, 0xcc, 0x44, 0x4c, 0x68, 0xcc, 0x45, 0x9e, 0x0c, 0x26, 0x62, 0xc0, 0x1e, 0xf5, 0x61, 0xb8,
	0x9a, 0x43, 0xfb, 0x70, 0x48, 0xe0, 0x76, 0x85, 0xdb, 0xfd, 0xa0, 0x20, 0x0e, 0x5a, 0xa3, 0x3b,
	0xd1, 0x2d, 0x31, 0x42, 0x26, 0x4d, 0x18, 0xb0, 0x8f, 0xd0, 0x5f, 0x82, 0xb4, 0xe3, 0xd5, 0x68,
	0x24, 0x78, 0xf0, 0x5e, 0x98, 0x87, 0xb9, 0x11, 0xa5, 0xc5, 0xb4, 0x0a, 0xdf, 0x08, 0xdc, 0x19,
	0xf0, 0x2d, 0xd3, 0x46, 0xd3, 0xc5, 0xff, 0x4c, 0x64, 0x01, 0x66, 0x5a, 0x1c, 0xad, 0x1d, 0x64,
	0x6d, 0xc7, 0xc4, 0x57, 0x9e, 0xe3, 0x87, 0x53, 0x94, 0xd1, 0x07, 0xec, 0x09, 0xe9, 0x4c, 0x0f,
	0xe9, 0x45, 0x98, 0x1f, 0x49, 0x24, 0xa1, 0xfd, 0x95, 0x80, 0x5a, 0xe1, 0x76, 0xd9, 0xf0, 0x4c,
	0x74, 0xcf, 0x7b, 0x8d, 0xfe, 0x1d, 0xe7, 0x1c, 0x64, 0x91, 0x31, 0xca, 0xb6, 0xba, 0x1d, 0xec,
	0x1a, 0x92, 0xd3, 0x32, 0xb5, 0xe2, 0xe5, 0xd3, 0x35, 0x14, 0x8a, 0x70, 0x5f, 0xcc, 0x20, 0x21,
	0xbb, 0x0e, 0xb3, 0x15, 0x6e, 0xeb, 0xd8, 0xa0, 0x6d, 0x0c, 0x3d, 0x47, 0xed, 0xd9, 0x70, 0xd8,
	0x53, 0xc9, 0xb0, 0xab, 0x90, 0x3b, 0x2b, 0x42, 0x9c, 0x61, 0xf9, 0xe3, 0x24, 0x8c, 0x57, 0xb8,
	0x2d, 0x7d, 0x22, 0xa0, 0x08, 0x16, 0xfb, 0xea, 0xf0, 0x15, 0x29, 0x5c, 0x86, 0xca, 0xb3, 0x0b,
	0x02, 0x93, 0xdb, 0xdb, 0x29, 0x4c, 0xb0, 0x32, 0xc5, 0x85, 0x0d, 0x07, 0x8e, 0x28, 0xec, 0x0f,
	0xd6, 0xca, 0x67, 0x02, 0x39, 0xe1, 0x0e, 0x59, 0x13, 0x66, 0x10, 0x41, 0x95, 0x8d, 0x0b, 0x43,
	0x93, 0xf2, 0xbe, 0x10, 0x50, 0x47, 0xec, 0x86, 0x27, 0xe7, 0xc8, 0x72, 0x1a, 0xac, 0x94, 0xff,
	0x02, 0x9c, 0x14, 0x79, 0x48, 0xe0, 0xa6, 0xe8, 0x26, 0x3f, 0x16, 0x26, 0x11, 0x20, 0x95, 0xf5,
	0x8b, 0x22, 0x93, 0xda, 0xde, 0xc1, 0x95, 0xc1, 0x8b, 0xa7, 0x09, 0xc3, 0x0e, 0xf8, 0x2b, 0x8f,
	0xce, 0xe7, 0x1f, 0x27, 0x7f, 0xbe, 0xf9, 0xfd, 0x58, 0x25, 0x47, 0xc7, 0x2a, 0xf9, 0x75, 0xac,
	0x92, 0x0f, 0x27, 0xea, 0xd8, 0xd1, 0x89, 0x3a, 0xf6, 0xf3, 0x44, 0x1d, 0x7b, 0xbd, 0x68, 0x3b,
	0x7e, 0xbd, 0x55, 0xd5, 0x4c, 0xda, 0x28, 0xf5, 0xc6, 0x8e, 0xfe, 0xef, 0xf6, 0xe3, 0x7f, 0xc6,
	0x83, 0x26, 0xf2, 0xea, 0x44, 0xf0, 0xe3, 0xf6, 0xf0, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x32,
	0x14, 0xb8, 0x5a, 0x4f, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	PublishEnergyTransferOffer(ctx context.Context, in *MsgPublishEnergyTransferOffer, opts ...grpc.CallOption) (*MsgPublishEnergyTransferOfferResponse, error)
	StartEnergyTransferRequest(ctx context.Context, in *MsgStartEnergyTransferRequest, opts ...grpc.CallOption) (*MsgStartEnergyTransferRequestResponse, error)
	EnergyTransferStartedRequest(ctx context.Context, in *MsgEnergyTransferStartedRequest, opts ...grpc.CallOption) (*MsgEnergyTransferStartedRequestResponse, error)
	EnergyTransferCompletedRequest(ctx context.Context, in *MsgEnergyTransferCompletedRequest, opts ...grpc.CallOption) (*MsgEnergyTransferCompletedRequestResponse, error)
	CancelEnergyTransferRequest(ctx context.Context, in *MsgCancelEnergyTransferRequest, opts ...grpc.CallOption) (*MsgCancelEnergyTransferRequestResponse, error)
	RemoveEnergyOffer(ctx context.Context, in *MsgRemoveEnergyOffer, opts ...grpc.CallOption) (*MsgRemoveEnergyOfferResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) PublishEnergyTransferOffer(ctx context.Context, in *MsgPublishEnergyTransferOffer, opts ...grpc.CallOption) (*MsgPublishEnergyTransferOfferResponse, error) {
	out := new(MsgPublishEnergyTransferOfferResponse)
	err := c.cc.Invoke(ctx, "/chain4energy.cfeev.cfeev.Msg/PublishEnergyTransferOffer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) StartEnergyTransferRequest(ctx context.Context, in *MsgStartEnergyTransferRequest, opts ...grpc.CallOption) (*MsgStartEnergyTransferRequestResponse, error) {
	out := new(MsgStartEnergyTransferRequestResponse)
	err := c.cc.Invoke(ctx, "/chain4energy.cfeev.cfeev.Msg/StartEnergyTransferRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) EnergyTransferStartedRequest(ctx context.Context, in *MsgEnergyTransferStartedRequest, opts ...grpc.CallOption) (*MsgEnergyTransferStartedRequestResponse, error) {
	out := new(MsgEnergyTransferStartedRequestResponse)
	err := c.cc.Invoke(ctx, "/chain4energy.cfeev.cfeev.Msg/EnergyTransferStartedRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) EnergyTransferCompletedRequest(ctx context.Context, in *MsgEnergyTransferCompletedRequest, opts ...grpc.CallOption) (*MsgEnergyTransferCompletedRequestResponse, error) {
	out := new(MsgEnergyTransferCompletedRequestResponse)
	err := c.cc.Invoke(ctx, "/chain4energy.cfeev.cfeev.Msg/EnergyTransferCompletedRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CancelEnergyTransferRequest(ctx context.Context, in *MsgCancelEnergyTransferRequest, opts ...grpc.CallOption) (*MsgCancelEnergyTransferRequestResponse, error) {
	out := new(MsgCancelEnergyTransferRequestResponse)
	err := c.cc.Invoke(ctx, "/chain4energy.cfeev.cfeev.Msg/CancelEnergyTransferRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RemoveEnergyOffer(ctx context.Context, in *MsgRemoveEnergyOffer, opts ...grpc.CallOption) (*MsgRemoveEnergyOfferResponse, error) {
	out := new(MsgRemoveEnergyOfferResponse)
	err := c.cc.Invoke(ctx, "/chain4energy.cfeev.cfeev.Msg/RemoveEnergyOffer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	PublishEnergyTransferOffer(context.Context, *MsgPublishEnergyTransferOffer) (*MsgPublishEnergyTransferOfferResponse, error)
	StartEnergyTransferRequest(context.Context, *MsgStartEnergyTransferRequest) (*MsgStartEnergyTransferRequestResponse, error)
	EnergyTransferStartedRequest(context.Context, *MsgEnergyTransferStartedRequest) (*MsgEnergyTransferStartedRequestResponse, error)
	EnergyTransferCompletedRequest(context.Context, *MsgEnergyTransferCompletedRequest) (*MsgEnergyTransferCompletedRequestResponse, error)
	CancelEnergyTransferRequest(context.Context, *MsgCancelEnergyTransferRequest) (*MsgCancelEnergyTransferRequestResponse, error)
	RemoveEnergyOffer(context.Context, *MsgRemoveEnergyOffer) (*MsgRemoveEnergyOfferResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) PublishEnergyTransferOffer(ctx context.Context, req *MsgPublishEnergyTransferOffer) (*MsgPublishEnergyTransferOfferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishEnergyTransferOffer not implemented")
}
func (*UnimplementedMsgServer) StartEnergyTransferRequest(ctx context.Context, req *MsgStartEnergyTransferRequest) (*MsgStartEnergyTransferRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartEnergyTransferRequest not implemented")
}
func (*UnimplementedMsgServer) EnergyTransferStartedRequest(ctx context.Context, req *MsgEnergyTransferStartedRequest) (*MsgEnergyTransferStartedRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnergyTransferStartedRequest not implemented")
}
func (*UnimplementedMsgServer) EnergyTransferCompletedRequest(ctx context.Context, req *MsgEnergyTransferCompletedRequest) (*MsgEnergyTransferCompletedRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnergyTransferCompletedRequest not implemented")
}
func (*UnimplementedMsgServer) CancelEnergyTransferRequest(ctx context.Context, req *MsgCancelEnergyTransferRequest) (*MsgCancelEnergyTransferRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelEnergyTransferRequest not implemented")
}
func (*UnimplementedMsgServer) RemoveEnergyOffer(ctx context.Context, req *MsgRemoveEnergyOffer) (*MsgRemoveEnergyOfferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveEnergyOffer not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_PublishEnergyTransferOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgPublishEnergyTransferOffer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).PublishEnergyTransferOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain4energy.cfeev.cfeev.Msg/PublishEnergyTransferOffer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).PublishEnergyTransferOffer(ctx, req.(*MsgPublishEnergyTransferOffer))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_StartEnergyTransferRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgStartEnergyTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).StartEnergyTransferRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain4energy.cfeev.cfeev.Msg/StartEnergyTransferRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).StartEnergyTransferRequest(ctx, req.(*MsgStartEnergyTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_EnergyTransferStartedRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgEnergyTransferStartedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).EnergyTransferStartedRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain4energy.cfeev.cfeev.Msg/EnergyTransferStartedRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).EnergyTransferStartedRequest(ctx, req.(*MsgEnergyTransferStartedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_EnergyTransferCompletedRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgEnergyTransferCompletedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).EnergyTransferCompletedRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain4energy.cfeev.cfeev.Msg/EnergyTransferCompletedRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).EnergyTransferCompletedRequest(ctx, req.(*MsgEnergyTransferCompletedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CancelEnergyTransferRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCancelEnergyTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CancelEnergyTransferRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain4energy.cfeev.cfeev.Msg/CancelEnergyTransferRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CancelEnergyTransferRequest(ctx, req.(*MsgCancelEnergyTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RemoveEnergyOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRemoveEnergyOffer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RemoveEnergyOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain4energy.cfeev.cfeev.Msg/RemoveEnergyOffer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RemoveEnergyOffer(ctx, req.(*MsgRemoveEnergyOffer))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chain4energy.cfeev.cfeev.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishEnergyTransferOffer",
			Handler:    _Msg_PublishEnergyTransferOffer_Handler,
		},
		{
			MethodName: "StartEnergyTransferRequest",
			Handler:    _Msg_StartEnergyTransferRequest_Handler,
		},
		{
			MethodName: "EnergyTransferStartedRequest",
			Handler:    _Msg_EnergyTransferStartedRequest_Handler,
		},
		{
			MethodName: "EnergyTransferCompletedRequest",
			Handler:    _Msg_EnergyTransferCompletedRequest_Handler,
		},
		{
			MethodName: "CancelEnergyTransferRequest",
			Handler:    _Msg_CancelEnergyTransferRequest_Handler,
		},
		{
			MethodName: "RemoveEnergyOffer",
			Handler:    _Msg_RemoveEnergyOffer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cfeev/cfeev/tx.proto",
}

func (m *MsgPublishEnergyTransferOffer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgPublishEnergyTransferOffer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgPublishEnergyTransferOffer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PlugType != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PlugType))
		i--
		dAtA[i] = 0x30
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Location != nil {
		{
			size, err := m.Location.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.Tariff != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Tariff))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ChargerId) > 0 {
		i -= len(m.ChargerId)
		copy(dAtA[i:], m.ChargerId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ChargerId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgPublishEnergyTransferOfferResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgPublishEnergyTransferOfferResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgPublishEnergyTransferOfferResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgStartEnergyTransferRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgStartEnergyTransferRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgStartEnergyTransferRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EnergyToTransfer != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.EnergyToTransfer))
		i--
		dAtA[i] = 0x38
	}
	if m.Collateral != nil {
		{
			size, err := m.Collateral.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if len(m.OfferedTariff) > 0 {
		i -= len(m.OfferedTariff)
		copy(dAtA[i:], m.OfferedTariff)
		i = encodeVarintTx(dAtA, i, uint64(len(m.OfferedTariff)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.OwnerAccountAddress) > 0 {
		i -= len(m.OwnerAccountAddress)
		copy(dAtA[i:], m.OwnerAccountAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.OwnerAccountAddress)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ChargerId) > 0 {
		i -= len(m.ChargerId)
		copy(dAtA[i:], m.ChargerId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ChargerId)))
		i--
		dAtA[i] = 0x1a
	}
	if m.EnergyTransferOfferId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.EnergyTransferOfferId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgStartEnergyTransferRequestResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgStartEnergyTransferRequestResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgStartEnergyTransferRequestResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgEnergyTransferStartedRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgEnergyTransferStartedRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgEnergyTransferStartedRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Info) > 0 {
		i -= len(m.Info)
		copy(dAtA[i:], m.Info)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Info)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ChargerId) > 0 {
		i -= len(m.ChargerId)
		copy(dAtA[i:], m.ChargerId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ChargerId)))
		i--
		dAtA[i] = 0x1a
	}
	if m.EnergyTransferId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.EnergyTransferId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgEnergyTransferStartedRequestResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgEnergyTransferStartedRequestResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgEnergyTransferStartedRequestResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgEnergyTransferCompletedRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgEnergyTransferCompletedRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgEnergyTransferCompletedRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Info) > 0 {
		i -= len(m.Info)
		copy(dAtA[i:], m.Info)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Info)))
		i--
		dAtA[i] = 0x2a
	}
	if m.UsedServiceUnits != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.UsedServiceUnits))
		i--
		dAtA[i] = 0x20
	}
	if len(m.ChargerId) > 0 {
		i -= len(m.ChargerId)
		copy(dAtA[i:], m.ChargerId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ChargerId)))
		i--
		dAtA[i] = 0x1a
	}
	if m.EnergyTransferId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.EnergyTransferId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgEnergyTransferCompletedRequestResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgEnergyTransferCompletedRequestResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgEnergyTransferCompletedRequestResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCancelEnergyTransferRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCancelEnergyTransferRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCancelEnergyTransferRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ErrorCode) > 0 {
		i -= len(m.ErrorCode)
		copy(dAtA[i:], m.ErrorCode)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ErrorCode)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ErrorInfo) > 0 {
		i -= len(m.ErrorInfo)
		copy(dAtA[i:], m.ErrorInfo)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ErrorInfo)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ChargerId) > 0 {
		i -= len(m.ChargerId)
		copy(dAtA[i:], m.ChargerId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ChargerId)))
		i--
		dAtA[i] = 0x1a
	}
	if m.EnergyTransferId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.EnergyTransferId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCancelEnergyTransferRequestResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCancelEnergyTransferRequestResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCancelEnergyTransferRequestResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgRemoveEnergyOffer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRemoveEnergyOffer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRemoveEnergyOffer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRemoveEnergyOfferResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRemoveEnergyOfferResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRemoveEnergyOfferResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgPublishEnergyTransferOffer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ChargerId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Tariff != 0 {
		n += 1 + sovTx(uint64(m.Tariff))
	}
	if m.Location != nil {
		l = m.Location.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.PlugType != 0 {
		n += 1 + sovTx(uint64(m.PlugType))
	}
	return n
}

func (m *MsgPublishEnergyTransferOfferResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgStartEnergyTransferRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.EnergyTransferOfferId != 0 {
		n += 1 + sovTx(uint64(m.EnergyTransferOfferId))
	}
	l = len(m.ChargerId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.OwnerAccountAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.OfferedTariff)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Collateral != nil {
		l = m.Collateral.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	if m.EnergyToTransfer != 0 {
		n += 1 + sovTx(uint64(m.EnergyToTransfer))
	}
	return n
}

func (m *MsgStartEnergyTransferRequestResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgEnergyTransferStartedRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.EnergyTransferId != 0 {
		n += 1 + sovTx(uint64(m.EnergyTransferId))
	}
	l = len(m.ChargerId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Info)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgEnergyTransferStartedRequestResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgEnergyTransferCompletedRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.EnergyTransferId != 0 {
		n += 1 + sovTx(uint64(m.EnergyTransferId))
	}
	l = len(m.ChargerId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.UsedServiceUnits != 0 {
		n += 1 + sovTx(uint64(m.UsedServiceUnits))
	}
	l = len(m.Info)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgEnergyTransferCompletedRequestResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCancelEnergyTransferRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.EnergyTransferId != 0 {
		n += 1 + sovTx(uint64(m.EnergyTransferId))
	}
	l = len(m.ChargerId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ErrorInfo)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ErrorCode)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCancelEnergyTransferRequestResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgRemoveEnergyOffer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgRemoveEnergyOfferResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgPublishEnergyTransferOffer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgPublishEnergyTransferOffer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgPublishEnergyTransferOffer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChargerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChargerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tariff", wireType)
			}
			m.Tariff = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Tariff |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Location", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Location == nil {
				m.Location = &Location{}
			}
			if err := m.Location.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlugType", wireType)
			}
			m.PlugType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PlugType |= PlugType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgPublishEnergyTransferOfferResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgPublishEnergyTransferOfferResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgPublishEnergyTransferOfferResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgStartEnergyTransferRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgStartEnergyTransferRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgStartEnergyTransferRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnergyTransferOfferId", wireType)
			}
			m.EnergyTransferOfferId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EnergyTransferOfferId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChargerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChargerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnerAccountAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OwnerAccountAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OfferedTariff", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OfferedTariff = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Collateral", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Collateral == nil {
				m.Collateral = &types.Coin{}
			}
			if err := m.Collateral.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnergyToTransfer", wireType)
			}
			m.EnergyToTransfer = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EnergyToTransfer |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgStartEnergyTransferRequestResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgStartEnergyTransferRequestResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgStartEnergyTransferRequestResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgEnergyTransferStartedRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgEnergyTransferStartedRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgEnergyTransferStartedRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnergyTransferId", wireType)
			}
			m.EnergyTransferId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EnergyTransferId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChargerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChargerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Info", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Info = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgEnergyTransferStartedRequestResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgEnergyTransferStartedRequestResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgEnergyTransferStartedRequestResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgEnergyTransferCompletedRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgEnergyTransferCompletedRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgEnergyTransferCompletedRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnergyTransferId", wireType)
			}
			m.EnergyTransferId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EnergyTransferId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChargerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChargerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UsedServiceUnits", wireType)
			}
			m.UsedServiceUnits = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UsedServiceUnits |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Info", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Info = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgEnergyTransferCompletedRequestResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgEnergyTransferCompletedRequestResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgEnergyTransferCompletedRequestResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCancelEnergyTransferRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCancelEnergyTransferRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCancelEnergyTransferRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnergyTransferId", wireType)
			}
			m.EnergyTransferId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EnergyTransferId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChargerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChargerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrorInfo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ErrorInfo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrorCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ErrorCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCancelEnergyTransferRequestResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCancelEnergyTransferRequestResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCancelEnergyTransferRequestResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRemoveEnergyOffer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRemoveEnergyOffer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRemoveEnergyOffer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRemoveEnergyOfferResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRemoveEnergyOfferResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRemoveEnergyOfferResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
